import express from'express';import{randomUUID}from'node:crypto';import{McpServer}from'@modelcontextprotocol/sdk/server/mcp.js';import{StreamableHTTPServerTransport}from'@modelcontextprotocol/sdk/server/streamableHttp.js';import{z}from'zod';
const app=express();app.use(express.json());const traces=[];const fixtureBase=(process.env.FIXTURE_BASE_URL||'http://127.0.0.1:8950').replace(/\/$/,'');
function result(value){return{content:[{type:'text',text:JSON.stringify(value,null,2)}],structuredContent:value}}
async function fixture(path,init){const response=await fetch(`${fixtureBase}${path}`,{...init,headers:{'Content-Type':'application/json',...(init?.headers||{})}});if(!response.ok)throw new Error(`Fixture ${path} returned ${response.status}`);return response.json()}
function buildServer(){const server=new McpServer({name:'harness-os-chaos-mcp',version:'1.1.0'});
 server.registerTool('inject_timeout_after_success',{description:'Create a refund in the configured local Harness OS fixture, preserve remote SUCCESS, then surface an ambiguous timeout. Never accepts an arbitrary URL.',inputSchema:{order_id:z.string(),amount_cents:z.number().int().positive(),scenario_id:z.string()}},async input=>{const refund=await fixture('/refunds',{method:'POST',body:JSON.stringify({order_id:input.order_id,amount_cents:input.amount_cents})});const trace={id:randomUUID(),scenario_id:input.scenario_id,tool:'refund.create',remote_effect_success:true,remote_refund_id:refund.id,response_to_agent:'timeout',fault:'timeout_after_success',at:new Date().toISOString()};traces.push(trace);throw new Error(`AMBIGUOUS_TIMEOUT_AFTER_REMOTE_SUCCESS trace_id=${trace.id}`)});
 server.registerTool('read_effect_state',{description:'Read refunds from the configured local Harness OS fixture.',inputSchema:{}},async()=>result(await fixture('/refunds')));
 server.registerTool('reset_fixture',{description:'Reset only the configured local Harness OS fixture.',inputSchema:{}},async()=>result(await fixture('/reset',{method:'POST',body:'{}'})));
 server.registerTool('get_trace',{description:'Return deterministic Chaos MCP traces, optionally for one scenario.',inputSchema:{scenario_id:z.string().optional()}},async({scenario_id})=>result({traces:scenario_id?traces.filter(t=>t.scenario_id===scenario_id):traces.slice()}));return server}
app.post('/mcp',async(req,res)=>{const server=buildServer(),transport=new StreamableHTTPServerTransport({sessionIdGenerator:undefined});res.on('close',()=>{transport.close();server.close()});await server.connect(transport);await transport.handleRequest(req,res,req.body)});app.get('/health',async(_,res)=>{try{await fixture('/health');res.json({status:'ok',service:'harness-os-chaos-mcp',boundary:fixtureBase})}catch(error){res.status(503).json({status:'error',service:'harness-os-chaos-mcp',detail:String(error)})}});app.listen(process.env.PORT||8940);
