import React,{useEffect,useMemo,useRef,useState}from'react';
import{Activity,AlertTriangle,CheckCircle2,ChevronRight,Clock3,ExternalLink,GitBranch,GitPullRequest,Globe2,LockKeyhole,Play,Plus,RefreshCw,Server,ShieldCheck,TerminalSquare,XCircle}from'lucide-react';
import{api,subscribe}from'./lib/api';
import'./mission-control.css';

type Tab='run'|'evidence'|'integrations'|'targets';
const gateLabels:any={sandbox:'Sandbox',human_approval:'Human approval',github_pr:'GitHub PR',qodo_review:'Qodo review',exact_replay:'Exact replay',safety_case:'Safety Case',repository_inspection:'Repository inspection',runtime_evidence:'Runtime evidence'};
const deriveName=(url:string)=>{try{return new URL(url).pathname.split('/').filter(Boolean).at(-1)||''}catch{return''}};
const cls=(s:string)=>String(s||'unknown').toLowerCase().replaceAll('_','-').replaceAll(' ','-');

export default function MissionControl(){
 const[tab,setTab]=useState<Tab>('run'),[agents,setAgents]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[selectedId,setSelectedId]=useState(''),[snapshot,setSnapshot]=useState<any>(),[services,setServices]=useState<any[]>([]),[tf,setTf]=useState<any>(),[integrations,setIntegrations]=useState<any>(),[busy,setBusy]=useState(''),[error,setError]=useState(''),[connectOpen,setConnectOpen]=useState(false),[confirming,setConfirming]=useState(false),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[displayName,setDisplayName]=useState(''),[nameTouched,setNameTouched]=useState(false);const requestToken=useRef(0);
 const selected=agents.find(a=>a.id===selectedId)||agents[0];
 const selectedCampaign=useMemo(()=>campaigns.find(c=>c.agent_id===selected?.id&&['WAITING_APPROVAL','RUNNING','PLANNING','PAUSED'].includes(c.status))||campaigns.find(c=>c.agent_id===selected?.id),[campaigns,selected?.id]);
 const campaign=snapshot?.campaign;const cert=snapshot?.certification;const approval=snapshot?.approval;const events=snapshot?.events||[];

 async function loadCore(refreshQodo=false){const token=++requestToken.current;setError('');try{const[a,c,s,t]=await Promise.all([api.agents(),api.campaigns(),api.publicServices(),api.trueforgeStatus()]);if(token!==requestToken.current)return;setAgents(a||[]);setCampaigns(c||[]);setServices(s.services||[]);setTf(t);const chosen=(selectedId?c.find((x:any)=>x.agent_id===selectedId&&['WAITING_APPROVAL','RUNNING','PLANNING','PAUSED'].includes(x.status))||c.find((x:any)=>x.agent_id===selectedId):undefined)||c.find((x:any)=>x.status==='WAITING_APPROVAL')||c.find((x:any)=>['RUNNING','PLANNING','PAUSED'].includes(x.status))||c[0];const snap=await api.operatorSnapshot(chosen?.id,refreshQodo);if(token===requestToken.current)setSnapshot(snap)}catch(e:any){if(token===requestToken.current)setError(e.message)}}
 useEffect(()=>{loadCore(false);const t=setInterval(()=>loadCore(false),5000);return()=>{clearInterval(t);requestToken.current++}},[]);
 useEffect(()=>{if(!selectedId&&agents[0])setSelectedId(agents[0].id)},[agents,selectedId]);
 useEffect(()=>{if(!selectedCampaign?.id)return;let alive=true;api.operatorSnapshot(selectedCampaign.id,false).then(x=>{if(alive){setSnapshot(x);setConfirming(false)}}).catch(e=>alive&&setError(e.message));const stop=subscribe(selectedCampaign.id,()=>api.operatorSnapshot(selectedCampaign.id,false).then(x=>alive&&setSnapshot(x)).catch(()=>{}),()=>{});return()=>{alive=false;stop()}},[selectedCampaign?.id]);

 async function connect(e:React.FormEvent){e.preventDefault();setBusy('connect');setError('');try{const name=displayName.trim()||deriveName(repo.trim());if(!name)throw new Error('Enter a valid public GitHub repository URL.');const a=await api.connectTarget({repository_url:repo.trim(),branch:branch.trim()||'main',name,harness_type:'TrueForge',config_path:null});setSelectedId(a.id);setRepo('');setDisplayName('');setNameTouched(false);setConnectOpen(false);await loadCore(false)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function inspect(){if(!selected)return;setBusy('inspect');setError('');try{const c=await api.inspectTarget(selected.id);setCampaigns(v=>[c,...v.filter(x=>x.id!==c.id)]);setSnapshot(await api.operatorSnapshot(c.id,false));setTab('run')}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function retryTrueForge(){setBusy('trueforge');setError('');try{setTf(await api.trueforgeStatus())}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function loadIntegrations(){setBusy('integrations');try{setIntegrations(await api.integrations())}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function decide(action:'approve'|'reject'){if(!approval?.id||approval.campaign_id!==campaign?.id){setError('Approval context changed. Refresh before deciding.');return}setBusy(action);setError('');try{await api.decide(approval.id,action,action==='approve'?'Operator reviewed the exact bound GitHub MCP calls in Mission Control and confirmed approval before execution.':'Operator rejected the proposed irreversible GitHub MCP calls.');setConfirming(false);setSnapshot(await api.operatorSnapshot(campaign.id,true))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 function pickTarget(id:string){requestToken.current++;setSelectedId(id);setSnapshot(undefined);setConfirming(false)}

 const next=cert?.next_gate||((campaign?.status==='ERROR')?'runtime_evidence':'repository_inspection');const waiting=approval?.status==='PENDING'?'YOUR APPROVAL':campaign?.status==='ERROR'?'RUNTIME RECOVERY':gateLabels[next]||'NEXT EVIDENCE';const lastEvent=events.at(-1);const online=services.filter(s=>s.reachable).length;
 const tfBad=tf&&tf.status!=='CONNECTED';
 return <main className="mc-shell">
  <header className="mc-header"><div className="mc-brand"><ShieldCheck/><div><strong>Harness OS</strong><span>Agent Safety Mission Control</span></div></div><div className="mc-header-right"><span className={`mc-runtime ${tf?.status==='CONNECTED'?'ok':'bad'}`}><i/>{tf?.status||'CHECKING'} TrueForge</span><span className="mc-runtime ok"><Globe2/>{online}/{services.length||2} public</span></div></header>

  <div className="mc-topline"><div><span>ACTIVE TARGET</span><select value={selected?.id||''} onChange={e=>pickTarget(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name} — {a.branch}</option>)}</select></div><div className="mc-target-url">{selected?.repository_url?.startsWith('http')?<a href={selected.repository_url} target="_blank" rel="noreferrer">{selected.repository_url}<ExternalLink/></a>:<span>{selected?.repository_url||'No repository connected'}</span>}</div><button type="button" className="mc-secondary" onClick={()=>setConnectOpen(v=>!v)}><Plus/>{connectOpen?'Close':'Connect repo'}</button><button type="button" className="mc-primary" onClick={inspect} disabled={!selected||busy==='inspect'}><Play/>{busy==='inspect'?'Starting…':'Inspect with TrueForge'}</button></div>

  {connectOpen&&<form className="mc-connect" onSubmit={connect}><label>Repository URL<input required value={repo} placeholder="https://github.com/owner/repository" onChange={e=>{const v=e.target.value;setRepo(v);if(!nameTouched)setDisplayName(deriveName(v))}}/></label><label>Branch<input required value={branch} onChange={e=>setBranch(e.target.value)}/></label><label>Display name<input value={displayName} placeholder="Auto from repository" onChange={e=>{setNameTouched(true);setDisplayName(e.target.value)}}/></label><button className="mc-primary" disabled={busy==='connect'}>{busy==='connect'?'Connecting…':'Connect repository'}</button></form>}

  {tfBad&&<section className="mc-recovery"><div><AlertTriangle/><div><strong>TrueForge needs attention</strong><p>{tf.detail||'The runtime did not answer the health probe.'}</p><small>{tf.diagnosis}</small></div></div><div className="mc-recovery-meta"><code>{tf.base_url||'TRUEFORGE_BASE_URL'}</code><span>probe {tf.probe_timeout_seconds||4}s</span><button type="button" className="mc-secondary" onClick={retryTrueForge} disabled={busy==='trueforge'}><RefreshCw className={busy==='trueforge'?'spin':''}/>{busy==='trueforge'?'Retrying…':'Retry connection'}</button></div></section>}
  {error&&<div className="mc-error"><XCircle/>{error}<button type="button" onClick={()=>setError('')}>Dismiss</button></div>}

  <nav className="mc-tabs" aria-label="Mission control sections">{(['run','evidence','integrations','targets'] as Tab[]).map(t=><button type="button" key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);if(t==='integrations'&&!integrations)loadIntegrations()}}>{t==='run'?'Live Run':t==='evidence'?'Evidence':t==='integrations'?'Runtime Stack':'Targets'}</button>)}</nav>

  {tab==='run'&&<section className="mc-run">
   <div className="mc-state-grid"><article><span><Activity/>WHAT IT'S DOING</span><strong>{campaign?.status==='ERROR'?'Recovering runtime':gateLabels[next]||'Ready to inspect'}</strong><p>{campaign?.current_stage||'Choose a repository and start a TrueForge inspection.'}</p></article><article className={approval?.status==='PENDING'?'attention':''}><span><Clock3/>WHAT IT'S WAITING ON</span><strong>{waiting}</strong><p>{approval?.status==='PENDING'?'TrueForge is paused before the irreversible GitHub write.':campaign?.status==='ERROR'?'Fix the runtime connection, then retry.':'The next evidence gate must complete before the run advances.'}</p></article><article><span><CheckCircle2/>WHAT IT DID</span><strong>{lastEvent?.title||'No evidence yet'}</strong><p>{lastEvent?.detail||'Execution history will appear here as TrueForge acts.'}</p></article></div>
   <div className="mc-runbar"><span className={`mc-status ${cls(campaign?.status||'ready')}`}>{campaign?.status||'READY'}</span><span>Target <b>{snapshot?.target?.name||selected?.name||'—'}</b></span><span>Session <code>{campaign?.trueforge_session_id||'not started'}</code></span><span>Stage <code>{cert?.stage||campaign?.current_stage||'idle'}</code></span><button type="button" className="mc-icon-btn" onClick={()=>loadCore(true)}><RefreshCw/>Sync</button></div>
   <div className="mc-gates">{cert?.generic?<><div className={`mc-gate ${campaign?.status==='COMPLETED'?'done':'current'}`}><TerminalSquare/><span>Repository inspection</span><b>{campaign?.status==='COMPLETED'?'DONE':'CURRENT'}</b></div><ChevronRight/><div className="mc-gate locked"><ShieldCheck/><span>Safety findings</span><b>EVIDENCE-DRIVEN</b></div></>:['sandbox','human_approval','github_pr','qodo_review','exact_replay','safety_case'].map((g,i)=>{const passed=!!cert?.gates?.[g]?.passed;const current=cert?.next_gate===g;return <React.Fragment key={g}><div className={`mc-gate ${passed?'done':current?'current':'locked'}`}>{passed?<CheckCircle2/>:current?<Clock3/>:<LockKeyhole/>}<span>{gateLabels[g]}</span><b>{passed?'VERIFIED':current?'CURRENT':'LOCKED'}</b></div>{i<5&&<ChevronRight/>}</React.Fragment>})}</div>
   {approval?.status==='PENDING'&&approval.campaign_id===campaign?.id&&<section className="mc-approval"><div className="mc-approval-title"><LockKeyhole/><div><span>IRREVERSIBLE STEP — PAUSED BEFORE EXECUTION</span><h2>Review the exact GitHub MCP scope</h2><p>Nothing below executes until you confirm.</p></div></div><div className="mc-scope">{(approval.approved_targets||[]).map((t:any)=><article key={t.tool_call_id}><GitPullRequest/><div><strong>{t.tool}</strong><span>{t.repository} · {t.branch||'tool-selected branch'}</span></div><code>{t.tool_call_id}</code></article>)}</div>{!confirming?<div className="mc-actions"><button type="button" className="mc-danger" onClick={()=>decide('reject')} disabled={!!busy}><XCircle/>Reject</button><button type="button" className="mc-primary" onClick={()=>setConfirming(true)}><ShieldCheck/>Review & approve</button></div>:<div className="mc-confirm"><div><strong>Confirm approval</strong><p>Only the bound calls shown above will resume.</p></div><button type="button" className="mc-secondary" onClick={()=>setConfirming(false)}>Back</button><button type="button" className="mc-primary" onClick={()=>decide('approve')} disabled={busy==='approve'}>{busy==='approve'?'Approving…':'Confirm & resume TrueForge'}</button></div>}</section>}
   <div className="mc-feed"><div className="mc-section-title"><Activity/><strong>Live causal trace</strong><span>{events.length} persisted events</span></div>{events.length?events.slice(-8).reverse().map((e:any)=><article key={e.id||e.sequence}><i/><div><strong>{e.title||e.event_type}</strong><p>{e.detail}</p><small>{e.source||'HARNESS OS'} · {e.timestamp?new Date(e.timestamp).toLocaleTimeString():`#${e.sequence}`}</small></div></article>):<div className="mc-empty">Start an inspection to see TrueForge decisions, tool calls, waits and evidence here.</div>}</div>
  </section>}

  {tab==='evidence'&&<section className="mc-panel"><div className="mc-section-title"><ShieldCheck/><strong>Evidence inspector</strong><span>backend-authoritative</span></div><div className="mc-evidence-grid"><article><span>Campaign</span><strong>{campaign?.id||'No active campaign'}</strong><pre>{JSON.stringify({status:campaign?.status,stage:campaign?.current_stage,kind:campaign?.campaign_kind},null,2)}</pre></article><article><span>Certification</span><strong>{cert?.next_gate||'Not started'}</strong><pre>{JSON.stringify(cert?.gates||{},null,2)}</pre></article><article><span>Approval</span><strong>{approval?.status||'NONE'}</strong><pre>{JSON.stringify(approval?{id:approval.id,status:approval.status,targets:approval.approved_targets}:null,null,2)}</pre></article></div></section>}

  {tab==='integrations'&&<section className="mc-panel"><div className="mc-section-title"><Server/><strong>Runtime stack</strong><button type="button" className="mc-icon-btn" onClick={loadIntegrations}><RefreshCw/>Refresh</button></div><div className="mc-integration-grid">{(integrations?.integrations||[]).map((i:any)=><article key={i.name} className={cls(i.status)}><div><i/><strong>{i.name}</strong><span>{i.status}</span></div><p>{i.detail}</p>{i.href&&<a href={i.href} target="_blank" rel="noreferrer">Inspect evidence <ExternalLink/></a>}</article>)}</div><div className="mc-service-row">{services.map(s=><a key={s.name} href={s.url} target="_blank" rel="noreferrer" className={s.reachable?'online':'offline'}><Globe2/><div><strong>{s.name}</strong><span>{s.reachable?`ONLINE · ${s.latency_ms} ms`:`OFFLINE${s.http_status?` · HTTP ${s.http_status}`:''}`}</span></div><ExternalLink/></a>)}</div></section>}

  {tab==='targets'&&<section className="mc-panel"><div className="mc-section-title"><GitBranch/><strong>Connected repositories</strong><button type="button" className="mc-primary compact" onClick={()=>setConnectOpen(true)}><Plus/>Add repository</button></div><div className="mc-target-list">{agents.map(a=><button type="button" key={a.id} className={selected?.id===a.id?'selected':''} onClick={()=>{pickTarget(a.id);setTab('run')}}><div><strong>{a.name}</strong><span>{a.repository_url}</span></div><div><b>{a.status}</b><span>{a.branch}</span><span>Risk {a.risk||'UNKNOWN'}</span></div><ChevronRight/></button>)}</div></section>}
 </main>
}
