import React,{useEffect,useMemo,useRef,useState}from'react';
import{Activity,AlertTriangle,CheckCircle2,ChevronRight,Clock3,ExternalLink,GitBranch,GitPullRequest,Globe2,LockKeyhole,Play,Plus,RefreshCw,Server,ShieldCheck,TerminalSquare,XCircle}from'lucide-react';
import{api,subscribe}from'./lib/api';
import'./mission-control.css';

type Tab='run'|'evidence'|'integrations'|'targets';
const ACTIVE=['WAITING_APPROVAL','RUNNING','PLANNING','PAUSED'];
const HOSTED_JUDGE=import.meta.env.VITE_HOSTED_JUDGE==='true';
const gateLabels:any={sandbox:'Sandbox',human_approval:'Human approval',github_pr:'GitHub PR',qodo_review:'Qodo review',exact_replay:'Exact replay',safety_case:'Safety Case',repository_inspection:'Repository inspection',runtime_evidence:'Runtime evidence'};
const deriveName=(url:string)=>{try{const parts=new URL(url).pathname.split('/').filter(Boolean);return parts.length?parts[parts.length-1]:''}catch{return''}};
const cls=(s:string)=>String(s||'unknown').toLowerCase().replace(/_/g,'-').replace(/ /g,'-');

export default function MissionControl(){
 const[tab,setTab]=useState<Tab>('run'),[agents,setAgents]=useState<any[]>([]),[campaigns,setCampaigns]=useState<any[]>([]),[selectedId,setSelectedId]=useState(''),[snapshot,setSnapshot]=useState<any>(),[services,setServices]=useState<any[]>([]),[tf,setTf]=useState<any>(),[integrations,setIntegrations]=useState<any>(),[busy,setBusy]=useState(''),[error,setError]=useState(''),[connectOpen,setConnectOpen]=useState(false),[confirming,setConfirming]=useState(false),[repo,setRepo]=useState(''),[branch,setBranch]=useState('main'),[displayName,setDisplayName]=useState(''),[nameTouched,setNameTouched]=useState(false);
 const requestToken=useRef(0),selectedRef=useRef('');
 const selected=agents.find(a=>a.id===selectedId)||(!selectedId?agents[0]:undefined);
 const selectedCampaign=useMemo(()=>campaigns.find(c=>c.agent_id===selected?.id&&ACTIVE.includes(c.status))||campaigns.find(c=>c.agent_id===selected?.id),[campaigns,selected?.id]);
 const campaign=snapshot?.campaign,cert=snapshot?.certification,approval=snapshot?.approval,events=snapshot?.events||[];
 useEffect(()=>{selectedRef.current=selectedId},[selectedId]);

 async function loadCore(refreshQodo=false,targetOverride?:string){
  const token=++requestToken.current,targetId=targetOverride!==undefined?targetOverride:selectedRef.current;setError('');
  try{
   const[a,c]=await Promise.all([api.agents(),api.campaigns()]);if(token!==requestToken.current)return;
   setAgents(a||[]);setCampaigns(c||[]);
   const effectiveTarget=targetId||((a||[])[0]?.id||'');
   const chosen=effectiveTarget?(c||[]).find((x:any)=>x.agent_id===effectiveTarget&&ACTIVE.includes(x.status))||(c||[]).find((x:any)=>x.agent_id===effectiveTarget):undefined;
   const snap=await api.operatorSnapshot(chosen?.id,refreshQodo,effectiveTarget||undefined);
   if(token===requestToken.current&&(!effectiveTarget||selectedRef.current===effectiveTarget||!selectedRef.current))setSnapshot(snap);
  }catch(e:any){if(token===requestToken.current)setError(e.message)}
 }
 async function loadRuntime(force=false){
  const[s,t]=await Promise.all([api.publicServices(force),api.trueforgeStatus(force)]);setServices(s.services||[]);setTf(t);
 }
 useEffect(()=>{loadCore(false,selectedId);const timer=setInterval(()=>loadCore(false,selectedId),5000);return()=>{clearInterval(timer);requestToken.current++}},[selectedId]);
 useEffect(()=>{loadRuntime(false).catch(e=>setError(e.message))},[]);
 useEffect(()=>{if(!selectedId&&agents[0]){selectedRef.current=agents[0].id;setSelectedId(agents[0].id)}},[agents,selectedId]);
 useEffect(()=>{
  if(!selectedCampaign?.id||selectedCampaign.agent_id!==selected?.id)return;
  let alive=true;const campaignId=selectedCampaign.id,targetId=selected.id;const token=++requestToken.current;
  api.operatorSnapshot(campaignId,false,targetId).then(x=>{if(alive&&token===requestToken.current&&selectedRef.current===targetId){setSnapshot(x);setConfirming(false)}}).catch(e=>alive&&setError(e.message));
  const stop=subscribe(campaignId,()=>api.operatorSnapshot(campaignId,false,targetId).then(x=>{if(alive&&selectedRef.current===targetId)setSnapshot(x)}).catch(()=>{}),()=>{});
  return()=>{alive=false;stop()}
 },[selectedCampaign?.id,selected?.id]);

 async function connect(e:React.FormEvent){e.preventDefault();setBusy('connect');setError('');try{const name=displayName.trim()||deriveName(repo.trim());if(!name)throw new Error('Enter a valid public GitHub repository URL.');const a=await api.connectTarget({repository_url:repo.trim(),branch:branch.trim()||'main',name,harness_type:'TrueForge',config_path:null});requestToken.current++;selectedRef.current=a.id;setSelectedId(a.id);setSnapshot(undefined);setRepo('');setDisplayName('');setNameTouched(false);setConnectOpen(false);await loadCore(false,a.id)}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function inspect(){if(!selected)return;const targetId=selected.id,token=++requestToken.current;setBusy('inspect');setError('');setSnapshot(undefined);setConfirming(false);try{const c=await api.inspectTarget(targetId);if(token!==requestToken.current||selectedRef.current!==targetId)return;setCampaigns(v=>[c,...v.filter(x=>x.id!==c.id)]);const snap=await api.operatorSnapshot(c.id,false,targetId);if(token===requestToken.current&&selectedRef.current===targetId)setSnapshot(snap);setTab('run')}catch(e:any){if(token===requestToken.current)setError(e.message)}finally{if(token===requestToken.current)setBusy('')}}
 async function retryTrueForge(){setBusy('trueforge');setError('');try{setTf(await api.trueforgeStatus(true))}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function loadIntegrations(){setBusy('integrations');try{setIntegrations(await api.integrations());const s=await api.publicServices(false);setServices(s.services||[])}catch(e:any){setError(e.message)}finally{setBusy('')}}
 async function decide(action:'approve'|'reject'){
  if(HOSTED_JUDGE){setConfirming(false);setError('The anonymous hosted judge build cannot resolve consequential approvals. Use the authenticated/local operator runtime for Allow or Deny.');return}
  if(!selected?.id||!campaign?.id||campaign.agent_id!==selected.id||!approval?.id||approval.campaign_id!==campaign.id){setConfirming(false);setError('Approval context changed or belongs to another target. Refresh before deciding.');return}
  const targetId=selected.id,campaignId=campaign.id,approvalId=approval.id;setBusy(action);setError('');
  try{await api.decide(approvalId,action,action==='approve'?'Operator reviewed the exact bound GitHub MCP calls in Mission Control and confirmed approval before execution.':'Operator rejected the proposed irreversible GitHub MCP calls.');if(selectedRef.current!==targetId)return;setConfirming(false);setSnapshot(await api.operatorSnapshot(campaignId,true,targetId))}catch(e:any){setError(e.message)}finally{setBusy('')}
 }
 function pickTarget(id:string){requestToken.current++;selectedRef.current=id;setSelectedId(id);setSnapshot(undefined);setConfirming(false);setError('')}

 const next=cert?.next_gate||((campaign?.status==='ERROR')?'runtime_evidence':'repository_inspection');
 const waiting=approval?.status==='PENDING'?'YOUR APPROVAL':campaign?.status==='ERROR'?'RUNTIME RECOVERY':gateLabels[next]||'NEXT EVIDENCE';
 const lastEvent=events.length?events[events.length-1]:undefined,online=services.filter((s:any)=>s.reachable).length,tfBad=tf&&tf.status!=='CONNECTED',tfRateLimited=tf?.status==='RATE_LIMITED',tfRetryAfter=Number(tf?.retry_after_seconds||0);
 return <main className="mc-shell">
  <header className="mc-header"><div className="mc-brand"><ShieldCheck/><div><strong>Harness OS</strong><span>Agent Safety Mission Control{HOSTED_JUDGE?' · Hosted Judge Demo':''}</span></div></div><div className="mc-header-right"><span className={`mc-runtime ${tf?.status==='CONNECTED'?'ok':'bad'}`}><i/>{tf?.status||'CHECKING'} TrueForge</span><span className="mc-runtime ok"><Globe2/>{online}/{services.length||2} public</span></div></header>
  <div className="mc-topline"><div><span>ACTIVE TARGET</span><select value={selected?.id||''} onChange={e=>pickTarget(e.target.value)}>{agents.map(a=><option key={a.id} value={a.id}>{a.name} — {a.branch}</option>)}</select></div><div className="mc-target-url">{selected?.repository_url?.startsWith('http')?<a href={selected.repository_url} target="_blank" rel="noreferrer">{selected.repository_url}<ExternalLink/></a>:<span>{selected?.repository_url||'No repository connected'}</span>}</div><button type="button" className="mc-secondary" onClick={()=>setConnectOpen(v=>!v)}><Plus/>{connectOpen?'Close':'Connect repo'}</button><button type="button" className="mc-primary" onClick={inspect} disabled={!selected||busy==='inspect'}><Play/>{busy==='inspect'?'Starting…':'Inspect with TrueForge'}</button></div>
  {connectOpen&&<form className="mc-connect" onSubmit={connect}><label>Repository URL<input required value={repo} placeholder="https://github.com/owner/repository" onChange={e=>{const v=e.target.value;setRepo(v);if(!nameTouched)setDisplayName(deriveName(v))}}/></label><label>Branch<input required value={branch} onChange={e=>setBranch(e.target.value)}/></label><label>Display name<input value={displayName} placeholder="Auto from repository" onChange={e=>{setNameTouched(true);setDisplayName(e.target.value)}}/></label><button className="mc-primary" disabled={busy==='connect'}>{busy==='connect'?'Connecting…':'Connect repository'}</button></form>}
  {tfBad&&<section className="mc-recovery"><div><AlertTriangle/><div><strong>{tfRateLimited?'TrueForge temporarily rate limited':'TrueForge needs attention'}</strong><p>{tf.detail||'The runtime did not answer the health probe.'}</p><small>{tf.diagnosis}</small>{tf.configuration_warning&&<small>{tf.configuration_warning}</small>}</div></div><div className="mc-recovery-meta"><code>{tf.base_url||'TRUEFORGE_BASE_URL'}</code><span>{tfRateLimited?`probe paused · retry in ~${tfRetryAfter||60}s`:`probe ${tf.probe_timeout_seconds||4}s`}</span><button type="button" className="mc-secondary" onClick={retryTrueForge} disabled={busy==='trueforge'||(tfRateLimited&&tfRetryAfter>0)}><RefreshCw className={busy==='trueforge'?'spin':''}/>{busy==='trueforge'?'Retrying…':tfRateLimited&&tfRetryAfter>0?`Retry in ${tfRetryAfter}s`:'Retry connection'}</button>{tfRateLimited&&<button type="button" className="mc-secondary" onClick={()=>setTab('evidence')}>Open Evidence</button>}</div></section>}
  {error&&<div className="mc-error"><XCircle/>{error}<button type="button" onClick={()=>setError('')}>Dismiss</button></div>}
  <nav className="mc-tabs" aria-label="Mission control sections">{(['run','evidence','integrations','targets'] as Tab[]).map(t=><button type="button" key={t} className={tab===t?'active':''} onClick={()=>{setTab(t);if(t==='integrations'&&!integrations)loadIntegrations()}}>{t==='run'?'Live Run':t==='evidence'?'Evidence':t==='integrations'?'Runtime Stack':'Targets'}</button>)}</nav>
  {tab==='run'&&<section className="mc-run">
   <div className="mc-state-grid"><article><span><Activity/>WHAT IT'S DOING</span><strong>{campaign?.status==='ERROR'?'Recovering runtime':gateLabels[next]||'Ready to inspect'}</strong><p>{campaign?.current_stage||'Choose a repository and start a TrueForge inspection.'}</p></article><article className={approval?.status==='PENDING'?'attention':''}><span><Clock3/>WHAT IT'S WAITING ON</span><strong>{waiting}</strong><p>{approval?.status==='PENDING'?'TrueForge is paused before the irreversible GitHub write.':campaign?.status==='ERROR'?'Fix the runtime connection, then retry.':'The next evidence gate must complete before the run advances.'}</p></article><article><span><CheckCircle2/>WHAT IT DID</span><strong>{lastEvent?.title||'No evidence yet'}</strong><p>{lastEvent?.detail||'Execution history will appear here as TrueForge acts.'}</p></article></div>
   <div className="mc-runbar"><span className={`mc-status ${cls(campaign?.status||'ready')}`}>{campaign?.status||'READY'}</span><span>Target <b>{snapshot?.target?.name||selected?.name||'—'}</b></span><span>Session <code>{campaign?.trueforge_session_id||'not started'}</code></span><span>Stage <code>{cert?.stage||campaign?.current_stage||'idle'}</code></span><button type="button" className="mc-icon-btn" onClick={()=>loadCore(true,selected?.id)}><RefreshCw/>Sync evidence</button></div>
   <div className="mc-gates">{cert?.generic?<><div className={`mc-gate ${campaign?.status==='COMPLETED'?'done':campaign?.status==='ERROR'?'locked':'current'}`}><TerminalSquare/><span>Repository inspection</span><b>{campaign?.status==='COMPLETED'?'DONE':campaign?.status==='ERROR'?'FAILED':'CURRENT'}</b></div><ChevronRight/><div className="mc-gate locked"><ShieldCheck/><span>Safety findings</span><b>EVIDENCE-DRIVEN</b></div></>:['sandbox','human_approval','github_pr','qodo_review','exact_replay','safety_case'].map((g,i)=>{const passed=!!cert?.gates?.[g]?.passed,current=cert?.next_gate===g;return <React.Fragment key={g}><div className={`mc-gate ${passed?'done':current?'current':'locked'}`}>{passed?<CheckCircle2/>:current?<Clock3/>:<LockKeyhole/>}<span>{gateLabels[g]}</span><b>{passed?'VERIFIED':current?'CURRENT':'LOCKED'}</b></div>{i<5&&<ChevronRight/>}</React.Fragment>})}</div>
   {approval?.status==='PENDING'&&approval.campaign_id===campaign?.id&&campaign?.agent_id===selected?.id&&<section className="mc-approval"><div className="mc-approval-title"><LockKeyhole/><div><span>IRREVERSIBLE STEP — PAUSED BEFORE EXECUTION</span><h2>Review the exact GitHub MCP scope</h2><p>{HOSTED_JUDGE?'Public judge view shows the bound scope but cannot resolve it.':'Nothing below executes until you confirm.'}</p></div></div><div className="mc-scope">{(approval.approved_targets||[]).map((t:any)=><article key={t.tool_call_id}><GitPullRequest/><div><strong>{t.tool}</strong><span>{t.repository} · {t.branch||'tool-selected branch'}</span></div><code>{t.tool_call_id}</code></article>)}</div>{HOSTED_JUDGE?<div className="mc-confirm"><div><strong>Approval protected</strong><p>Allow/Deny is disabled in this anonymous hosted judge build. Resolve it only from the authenticated/local operator runtime.</p></div></div>:!confirming?<div className="mc-actions"><button type="button" className="mc-danger" onClick={()=>decide('reject')} disabled={!!busy}><XCircle/>Reject</button><button type="button" className="mc-primary" onClick={()=>setConfirming(true)}><ShieldCheck/>Review & approve</button></div>:<div className="mc-confirm"><div><strong>Confirm approval</strong><p>Only the bound calls shown above will resume for <b>{selected?.name}</b>.</p></div><button type="button" className="mc-secondary" onClick={()=>setConfirming(false)}>Back</button><button type="button" className="mc-primary" onClick={()=>decide('approve')} disabled={busy==='approve'}>{busy==='approve'?'Approving…':'Confirm & resume TrueForge'}</button></div>}</section>}
   <div className="mc-feed"><div className="mc-section-title"><Activity/><strong>Live causal trace</strong><span>{events.length} persisted events</span></div>{events.length?events.slice(-8).reverse().map((e:any)=><article key={e.id||e.sequence}><i/><div><strong>{e.title||e.event_type}</strong><p>{e.detail}</p><small>{e.source||'HARNESS OS'} · {e.timestamp?new Date(e.timestamp).toLocaleTimeString():`#${e.sequence}`}</small></div></article>):<div className="mc-empty">Start an inspection to see TrueForge decisions, tool calls, waits and evidence here.</div>}</div>
  </section>}
  {tab==='evidence'&&<section className="mc-panel"><div className="mc-section-title"><ShieldCheck/><strong>Evidence inspector</strong><span>backend-authoritative</span></div><div className="mc-evidence-grid"><article><span>Campaign</span><strong>{campaign?.id||'No campaign for this target'}</strong><pre>{JSON.stringify({target:snapshot?.target?.name,status:campaign?.status,stage:campaign?.current_stage,kind:campaign?.campaign_kind},null,2)}</pre></article><article><span>Certification</span><strong>{cert?.next_gate||'Not started'}</strong><pre>{JSON.stringify(cert?.gates||{},null,2)}</pre></article><article><span>Approval</span><strong>{approval?.status||'NONE'}</strong><pre>{JSON.stringify(approval?{id:approval.id,campaign_id:approval.campaign_id,status:approval.status,targets:approval.approved_targets}:null,null,2)}</pre></article></div></section>}
  {tab==='integrations'&&<section className="mc-panel"><div className="mc-section-title"><Server/><strong>Runtime stack</strong><button type="button" className="mc-icon-btn" onClick={loadIntegrations}><RefreshCw/>Refresh</button></div><div className="mc-integration-grid">{(integrations?.integrations||[]).map((i:any)=><article key={i.name} className={cls(i.status)}><div><i/><strong>{i.name}</strong><span>{i.status}</span></div><p>{i.detail}</p>{i.name==='Qodo Review'&&i.proof&&<small>{i.proof.latest_author?`Verified author: ${i.proof.latest_author}`:'No verified author yet'}{i.proof.latest_at?` · ${new Date(i.proof.latest_at).toLocaleString()}`:''}</small>}{i.href&&<a href={i.href} target="_blank" rel="noreferrer">Inspect evidence <ExternalLink/></a>}</article>)}</div><div className="mc-service-row">{services.map((s:any)=><a key={s.name} href={s.url} target="_blank" rel="noreferrer" className={s.reachable?'online':'offline'}><Globe2/><div><strong>{s.name}</strong><span>{s.reachable?`ONLINE · ${s.latency_ms} ms`:`OFFLINE${s.http_status?` · HTTP ${s.http_status}`:''}`}</span></div><ExternalLink/></a>)}</div></section>}
  {tab==='targets'&&<section className="mc-panel"><div className="mc-section-title"><GitBranch/><strong>Connected repositories</strong><button type="button" className="mc-primary compact" onClick={()=>setConnectOpen(true)}><Plus/>Add repository</button></div><div className="mc-target-list">{agents.map(a=><button type="button" key={a.id} className={selected?.id===a.id?'selected':''} onClick={()=>{pickTarget(a.id);setTab('run')}}><div><strong>{a.name}</strong><span>{a.repository_url}</span></div><div><b>{a.status}</b><span>{a.branch}</span><span>Risk {a.risk||'UNKNOWN'}</span></div><ChevronRight/></button>)}</div></section>}
 </main>
}
